import React from "react";
import { StyleSheet, View, useWindowDimensions, ScrollView } from "react-native";
import RenderHtml from 'react-native-render-html';

export default function Terms(props) {

    const { width } = useWindowDimensions();

    const data = {
        html : `
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:center;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>POL&Iacute;TICA DE PRIVACIDAD</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>El presente Pol&iacute;tica de Privacidad establece los t&eacute;rminos en que VENTA DE ARTICULOS ARTESANALES usa y protege la informaci&oacute;n que es proporcionada por sus usuarios al momento de utilizar su sitio web. Esta compa&ntilde;&iacute;a est&aacute; comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de informaci&oacute;n personal con la cual usted pueda ser identificado, lo hacemos asegurando que s&oacute;lo se emplear&aacute; de acuerdo con los t&eacute;rminos de este documento. Sin embargo, esta Pol&iacute;tica de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta p&aacute;gina para asegurarse que est&aacute; de acuerdo con dichos cambios.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>INFORMACI&Oacute;N QUE ES RECOGIDA</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Nuestro sitio web podr&aacute; recoger informaci&oacute;n personal, por ejemplo: Nombre, informaci&oacute;n de contacto como&nbsp;su direcci&oacute;n de correo electr&oacute;nica e informaci&oacute;n demogr&aacute;fica. As&iacute; mismo cuando sea necesario podr&aacute; ser requerida informaci&oacute;n espec&iacute;fica para procesar alg&uacute;n pedido o realizar una entrega o facturaci&oacute;n.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>USO DE LA INFORMACI&Oacute;N RECOGIDA</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Nuestro sitio web emplea la informaci&oacute;n con el fin de proporcionar el mejor servicio posible, particularmente para mantener un registro de usuarios, de pedidos en caso que aplique, y mejorar nuestros productos y servicios. &nbsp;Es posible que sean enviados correos electr&oacute;nicos peri&oacute;dicamente a trav&eacute;s de nuestro sitio con ofertas especiales, nuevos productos y otra informaci&oacute;n publicitaria que consideremos relevante para usted o que pueda brindarle alg&uacute;n beneficio, estos correos electr&oacute;nicos ser&aacute;n enviados a la direcci&oacute;n que usted proporcione y podr&aacute;n ser cancelados en cualquier momento.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>AMANTOLI est&aacute; altamente comprometido para cumplir con el compromiso de mantener su informaci&oacute;n segura. Usamos los sistemas m&aacute;s avanzados y los actualizamos constantemente para asegurarnos que no exista ning&uacute;n acceso no autorizado.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>COOKIES</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener informaci&oacute;n respecto al tr&aacute;fico web, y tambi&eacute;n facilita las futuras visitas a una web recurrente. Otra funci&oacute;n que tienen las cookies es que con ellas la web pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Nuestro sitio web emplea las cookies para poder identificar las p&aacute;ginas que son visitadas y su frecuencia. Esta informaci&oacute;n es empleada &uacute;nicamente para an&aacute;lisis estad&iacute;stico y despu&eacute;s la informaci&oacute;n se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo, las cookies ayudan a proporcionar un mejor servicio de los sitios web, est&aacute;s no dan acceso a informaci&oacute;n de su ordenador ni de usted, a menos de que usted as&iacute; lo quiera y la proporcione directamente. Usted puede aceptar o negar el uso de cookies, sin embargo, la mayor&iacute;a de navegadores aceptan cookies autom&aacute;ticamente pues sirve para tener un mejor servicio web. Tambi&eacute;n usted puede cambiar la configuraci&oacute;n de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>ENLACES A TERCEROS</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Este sitio web pudiera contener en laces a otros sitios que pudieran ser de su inter&eacute;s. Una vez que usted de clic en estos enlaces y abandone nuestra p&aacute;gina, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los t&eacute;rminos o privacidad ni de la protecci&oacute;n de sus datos en esos otros sitios terceros. Dichos sitios est&aacute;n sujetos a sus propias pol&iacute;ticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted est&aacute; de acuerdo con estas.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>CONTROL DE SU INFORMACI&Oacute;N PERSONAL</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>En cualquier momento usted puede restringir la recopilaci&oacute;n o el uso de la informaci&oacute;n personal que es proporcionada a nuestro sitio web. &nbsp;Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opci&oacute;n de recibir informaci&oacute;n por correo electr&oacute;nico. &nbsp;En caso de que haya marcado la opci&oacute;n de recibir nuestro bolet&iacute;n o publicidad usted puede cancelarla en cualquier momento.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Esta compa&ntilde;&iacute;a no vender&aacute;, ceder&aacute; ni distribuir&aacute; la informaci&oacute;n personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con un orden judicial.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>VENTA DE ARTICULOS ARTESANALES Se reserva el derecho de cambiar los t&eacute;rminos de la presente Pol&iacute;tica de Privacidad en cualquier momento.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>CONSENTIMIENTO</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&iquest;C&Oacute;MO OBTIENEN MI CONSENTIMIENTO?</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Cuando nos provees tu informaci&oacute;n personal para completar una transacci&oacute;n, verificar tu tarjeta de cr&eacute;dito, crear una orden, concertar un env&iacute;o o hacer una devoluci&oacute;n, implicamos que aceptas la recolecci&oacute;n y uso por esa raz&oacute;n espec&iacute;fica solamente.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Si te pedimos tu informaci&oacute;n personal por una raz&oacute;n secundaria, como marketing, te pediremos directamente tu expreso consentimiento, o te daremos la oportunidad de negarte.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&iquest;C&Oacute;MO PUEDO ANULAR MI CONSENTIMIENTO?</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Si luego de haber aceptado cambias de opini&oacute;n, puedes anular tu consentimiento para que te contactemos, por la recolecci&oacute;n, uso o divulgaci&oacute;n de tu informaci&oacute;n, en cualquier momento, contact&aacute;ndonos a amantoli@gmail.com o escribi&eacute;ndonos a: AMANTOLI Colonia centro, Av. Reloj, HUEJUTLA DE REYES, HIDALGO, HIDALGO, 43080, M&eacute;xico</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>DIVULGACI&Oacute;N</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Podemos divulgar tu informaci&oacute;n personal si se nos requiere por ley o si violas nuestros T&eacute;rminos de Servicio.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>EDAD DE CONSENTIMIENTO</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Al utilizar este sitio, declaras que tienes al menos la mayor&iacute;a de edad en tu estado o provincia de residencia, o que tienes la mayor&iacute;a de edad en tu estado o provincia de residencia y que nos has dado tu consentimiento para permitir que cualquiera de tus dependientes menores use este sitio.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>PREGUNTAS E INFORMACI&Oacute;N DE CONTACTO</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Si quieres: acceder, corregir, enmendar o borrar cualquier informaci&oacute;n personal que poseamos sobre ti, registrar una queja, o simplemente quieres m&aacute;s informaci&oacute;n contacta a nuestro Oficial de Cumplimiento de Privacidad jamisnvte99@gmail.com o por correo postal a VENTA DE ARTICULOS ARTESANALES&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style='font-family:"Century Gothic",sans-serif;color:black;'>CAMBIOS A ESTA POL&Iacute;TICA DE PRIVACIDAD</span></strong></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Nos reservamos el derecho de modificar esta pol&iacute;tica de privacidad en cualquier momento, asique por favor rev&iacute;sala frecuentemente. &nbsp;Cambios y aclaraciones entrar&aacute;n en vigencia inmediatamente despu&eacute;s de su publicaci&oacute;n en el sitio web. &nbsp;Si hacemos cambios materiales a esta pol&iacute;tica, notificaremos aqu&iacute; que ha sido actualizada, por lo que cual est&aacute;s enterado de qu&eacute; informaci&oacute;n recopilamos, c&oacute;mo y bajo qu&eacute; circunstancias, si las hubiere, la utilizamos y/o divulgamos.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>Si nuestra tienda es adquirida o fusionada con otra empresa, tu informaci&oacute;n puede ser transferida a los nuevos propietarios, para que podamos seguir vendi&eacute;ndote productos.</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>&nbsp;</span></p>
        <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style='font-family:"Century Gothic",sans-serif;color:black;'>[Colina centro, Av. Reloj, HUEJUTLA DE REYES HIDALGO, HIDALGO, 43080, M&eacute;xico]</span></p>
        `
    }

    return (
        <View>
            <ScrollView contentContainerStyle={styles.container}>
                <RenderHtml
                    contentWidth={width}
                    source={data}
                />
            </ScrollView>
        </View>        
    );
}

const styles = StyleSheet.create({
    container: {
        paddingVertical: 20,
        paddingHorizontal: 20
    }
});
